# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "commander-2.20.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.0.tgz";
        sha512 = "7j2y+40w61zy6YC2iRNpUe/NwhNyoXrYpHMrSunaMG64nRnaf96zO/KMQR4OyN/UnE5KLyEBnKHd4aG3rskjpQ==";
      };
    };
    "comment-json-1.1.3" = {
      name = "comment-json";
      packageName = "comment-json";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/comment-json/-/comment-json-1.1.3.tgz";
        sha1 = "6986c3330fee0c4c9e00c2398cd61afa5d8f239e";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "configstore-5.0.0" = {
      name = "configstore";
      packageName = "configstore";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-5.0.0.tgz";
        sha512 = "eE/hvMs7qw7DlcB5JPRnthmrITuHMmACUJAp89v6PT6iOqzoLS7HRWhBtuHMlhNHo2AhUSA/3Dh1bKNJHcublQ==";
      };
    };
    "crypto-random-string-2.0.0" = {
      name = "crypto-random-string";
      packageName = "crypto-random-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-2.0.0.tgz";
        sha512 = "v1plID3y9r/lPhviJ1wrXpLeyUIGAZ2SHNYTEapm7/8A9nLPoyvVp3RK/EPFqn5kEznyWgYZNsRtYYIWbuG8KA==";
      };
    };
    "cspell-dict-companies-1.0.14" = {
      name = "cspell-dict-companies";
      packageName = "cspell-dict-companies";
      version = "1.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-companies/-/cspell-dict-companies-1.0.14.tgz";
        sha512 = "q4Xfe/vNteOs57r+YeEYzVsoQe2YGsi3uVMv06w0CkMa9y8llDXpBv7UJniLZVyW19491jlxIORkHx4i39MBUw==";
      };
    };
    "cspell-dict-cpp-1.1.23" = {
      name = "cspell-dict-cpp";
      packageName = "cspell-dict-cpp";
      version = "1.1.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-cpp/-/cspell-dict-cpp-1.1.23.tgz";
        sha512 = "vR24jdt3oCE51sfrTPEmzlw1JVltKNkUnS/1kjeauY5VAQjx04Q1XOBPHJHmTNRXdmcX/MvNFR8z3qbpC2pbMA==";
      };
    };
    "cspell-dict-django-1.0.12" = {
      name = "cspell-dict-django";
      packageName = "cspell-dict-django";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-django/-/cspell-dict-django-1.0.12.tgz";
        sha512 = "ChBzWNltlqIs7FSYjQV6qTdkxt4VFQJm2XGlfIoNUZ1kwrOpzVdEUuVpRhWtj9NVB6AJqJxWjm/HzVvMYEY2cg==";
      };
    };
    "cspell-dict-elixir-1.0.10" = {
      name = "cspell-dict-elixir";
      packageName = "cspell-dict-elixir";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-elixir/-/cspell-dict-elixir-1.0.10.tgz";
        sha512 = "Z+9K1ZHGo5XnbS2AZ5DG2bpEA9wJ4BdsTa69VIqPgZ6vEfVLqeMidk70FF0Y/DY49+Qyg3ngY0WyE5Je/Romzw==";
      };
    };
    "cspell-dict-en-gb-1.1.11" = {
      name = "cspell-dict-en-gb";
      packageName = "cspell-dict-en-gb";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-en-gb/-/cspell-dict-en-gb-1.1.11.tgz";
        sha512 = "UnmAeMDzf/YeXuI85BIaQzpArXlt+m+I9S9uy88nvUfq6goOfUFN8Axh0idDtqsFNoaMS5TgSzvjP7DgMXArYg==";
      };
    };
    "cspell-dict-en_us-1.2.18" = {
      name = "cspell-dict-en_us";
      packageName = "cspell-dict-en_us";
      version = "1.2.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-en_us/-/cspell-dict-en_us-1.2.18.tgz";
        sha512 = "P2TRblBVd9KOfwjvI5mxzEXMGBvvTIfqcKSQ+0RbpwC2S4ImW9k++LYxy9LtfSRmdSGjHbejYYtsrgvId1KcoA==";
      };
    };
    "cspell-dict-fullstack-1.0.17" = {
      name = "cspell-dict-fullstack";
      packageName = "cspell-dict-fullstack";
      version = "1.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-fullstack/-/cspell-dict-fullstack-1.0.17.tgz";
        sha512 = "XmFyvt5r9JXcIjnycFfZfc/82dmMBUSowL4Oa/Mubx0Tm66bKOTmhrDatXl96qo6J0cIoyoPXitsfj5YaDV17g==";
      };
    };
    "cspell-dict-golang-1.1.12" = {
      name = "cspell-dict-golang";
      packageName = "cspell-dict-golang";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-golang/-/cspell-dict-golang-1.1.12.tgz";
        sha512 = "G3D5CIJfwPdzpgM/N5d/9hImG637GHn3FUkPzC3Kz1QN2G6JTwTAYPnsKybvLE80U9PUwrylZTZBM+cRZSWPzQ==";
      };
    };
    "cspell-dict-haskell-1.0.2" = {
      name = "cspell-dict-haskell";
      packageName = "cspell-dict-haskell";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-haskell/-/cspell-dict-haskell-1.0.2.tgz";
        sha512 = "d+pFdRUGZjusiXRqWW05pZqeFKsR5Nvrp/8qlowp/mwNFRBoMzrrAHnP7DZrfo/zHHpzCR3SnmT0ImnCv2MDcQ==";
      };
    };
    "cspell-dict-html-symbol-entities-1.0.11" = {
      name = "cspell-dict-html-symbol-entities";
      packageName = "cspell-dict-html-symbol-entities";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-html-symbol-entities/-/cspell-dict-html-symbol-entities-1.0.11.tgz";
        sha512 = "8uqZOa+8jDg/FH1LPfwfgOWT/0+3CXPWoWf4t+SjEhNVRoih2HVweQZCwVr+CsmEHgVON8Tem3OWwz+e1zJwNA==";
      };
    };
    "cspell-dict-java-1.0.10" = {
      name = "cspell-dict-java";
      packageName = "cspell-dict-java";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-java/-/cspell-dict-java-1.0.10.tgz";
        sha512 = "GKgJ+HSii7Xp+LT0Gajy4ipcQgapwsM3fmmZS6pZBZMoodJ0BRzga6QZrBuJSHVhSBV4rFIPJwI4oBGYZCGSpQ==";
      };
    };
    "cspell-dict-latex-1.0.11" = {
      name = "cspell-dict-latex";
      packageName = "cspell-dict-latex";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-latex/-/cspell-dict-latex-1.0.11.tgz";
        sha512 = "z/mejOvZAHIL76wnk7i/RT1v1IkSCYlk1l8pLW8l/KA76MCdNAB5xA6zfyBCftbhEOBJA9Fx60JU2T2aba4isg==";
      };
    };
    "cspell-dict-lorem-ipsum-1.0.10" = {
      name = "cspell-dict-lorem-ipsum";
      packageName = "cspell-dict-lorem-ipsum";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-lorem-ipsum/-/cspell-dict-lorem-ipsum-1.0.10.tgz";
        sha512 = "UlboQ3xH+D3l+hemLO4J5yz8EM60SH91f1dJIy2s94AeePZXtwYh1hTFM5dEsXI2CAQkfTu3ZdPWflLsInPfrA==";
      };
    };
    "cspell-dict-php-1.0.11" = {
      name = "cspell-dict-php";
      packageName = "cspell-dict-php";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-php/-/cspell-dict-php-1.0.11.tgz";
        sha512 = "0aC8PWVqEVg5II9+U9DBcUv6k9x1DpclH7l5cbvoiR8u69O/LnVlnSol1nSdzAwBhC6fWQ9mfOiMyDIHNZ2GfA==";
      };
    };
    "cspell-dict-powershell-1.0.2" = {
      name = "cspell-dict-powershell";
      packageName = "cspell-dict-powershell";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-powershell/-/cspell-dict-powershell-1.0.2.tgz";
        sha512 = "BW2Bdpet0yRQKB+7HjA75O0aJnh1VjdnMLNYb1SLvow73uCsC8GpvYLtvFyDm0Q717FYKoPzuZiSrXhyHerNAw==";
      };
    };
    "cspell-dict-python-1.0.14" = {
      name = "cspell-dict-python";
      packageName = "cspell-dict-python";
      version = "1.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-python/-/cspell-dict-python-1.0.14.tgz";
        sha512 = "w8kevjvayndKkZqY4yt877UzGXUNTG6gB0zoeOCVxnAFFqTexVvmJ9Johc+eOdqd+dnUu6gF8XfX4ZdX5J+Rxw==";
      };
    };
    "cspell-dict-rust-1.0.10" = {
      name = "cspell-dict-rust";
      packageName = "cspell-dict-rust";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-rust/-/cspell-dict-rust-1.0.10.tgz";
        sha512 = "iwWMVqOMnkTtb2Z50pGs+x9HM6ghqVotVguqgeJUVD62gqjHMHOTXAw/p7e8VFMXEPfVJeCZg3KGT3Ut6b+8Zg==";
      };
    };
    "cspell-dict-scala-1.0.9" = {
      name = "cspell-dict-scala";
      packageName = "cspell-dict-scala";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-scala/-/cspell-dict-scala-1.0.9.tgz";
        sha512 = "wWMjYe4OLFqeQpHYqBoAlXCwEgANu4DuJIg8Vg9Ig8arzobWX9uzmSwsicyGKtCjyno99/MIHAhksTTr7ccMzQ==";
      };
    };
    "cspell-glob-0.1.11" = {
      name = "cspell-glob";
      packageName = "cspell-glob";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-glob/-/cspell-glob-0.1.11.tgz";
        sha512 = "1s9539g+AB+V0gX4TPfCvhwWYso/fKlWQIX5w31BuqLjV6e8542x9vpdO/GS7aq1y1vec4ocx0B9I/d1SGFDSg==";
      };
    };
    "cspell-io-4.0.17" = {
      name = "cspell-io";
      packageName = "cspell-io";
      version = "4.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-io/-/cspell-io-4.0.17.tgz";
        sha512 = "srJnvfTm9QdrAGPx7OIR6MIZeXJPgwWupderhy4ywDQKgds4Yj1w3f10JWzHgsfWAwExAaEs3GZ4fEMUeWhnAA==";
      };
    };
    "cspell-lib-4.0.25" = {
      name = "cspell-lib";
      packageName = "cspell-lib";
      version = "4.0.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-lib/-/cspell-lib-4.0.25.tgz";
        sha512 = "EltUo+BBx15gCCYuDQ2V/pSPu1xIje9mdzCaEDoTJXIl1J5QVONmc91sukXLNEoymG4cdoZlnd2xg4fV/orynQ==";
      };
    };
    "cspell-trie-lib-4.0.15" = {
      name = "cspell-trie-lib";
      packageName = "cspell-trie-lib";
      version = "4.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-trie-lib/-/cspell-trie-lib-4.0.15.tgz";
        sha512 = "k3P03msJJh6Fhic9db7kva3+VodhvywvxxB5Q8Y7qF1xCu9zL2Zeoi+gA8ziL1QtUFqAqpzbDNPfiHhz6BaJsQ==";
      };
    };
    "cspell-util-bundle-4.0.5" = {
      name = "cspell-util-bundle";
      packageName = "cspell-util-bundle";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-util-bundle/-/cspell-util-bundle-4.0.5.tgz";
        sha512 = "luu/xIjoTRt82eJJxf77fhgjU6XJve+CfoTyfejOj7niYDRvoZkt0rTSHPgTI6MADjaZxlCLleSihEgqidt5WQ==";
      };
    };
    "dot-prop-5.1.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-5.1.0.tgz";
        sha512 = "n1oC6NBF+KM9oVXtjmen4Yo7HyAVWV2UUl50dCYJdw2924K6dX9bf9TTTWaKtYlRn0FEtxG27KS80ayVLixxJA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "fs-extra-8.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz";
        sha512 = "yhlQgA6mnOJUKOsRUFsgJdQCvkKhcz8tlZG5HBQfReYZy46OwLcY+Zia0mtdHsOo9y/hP+CxMN0TU9QxoOtG4g==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "gensequence-2.1.3" = {
      name = "gensequence";
      packageName = "gensequence";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensequence/-/gensequence-2.1.3.tgz";
        sha512 = "qa/2k1YSyh6TGVtIMtmwv1tXfq7lkhR8pMtOExfZGuwyaqplMhUxyO/Wrw9fV+37B38WE6egpjSMcwyzlNOoHA==";
      };
    };
    "get-stdin-7.0.0" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-7.0.0.tgz";
        sha512 = "zRKcywvrXlXsA0v0i9Io4KDRaAw7+a1ZpjRwl9Wox8PFlVCCHra7E9c4kqXCoCM9nR5tBkaTTZRBoCm60bFqTQ==";
      };
    };
    "glob-7.1.4" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.4.tgz";
        sha512 = "hkLPepehmnKk41pUGm3sYxoFs/umurYfYJCerbXEyFIWcAzvpipAgVkBqqT9RBKMGjnq6kMuyYwha6csxbiM1A==";
      };
    };
    "graceful-fs-4.2.2" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.2.tgz";
        sha512 = "IItsdsea19BoLC7ELy13q1iJFNmd7ofZH5+X/pJr90/nRoPEX0DJo1dHDbgtYWOhJhcCgMDTOw84RZ72q6lB+Q==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "iterable-to-stream-1.0.1" = {
      name = "iterable-to-stream";
      packageName = "iterable-to-stream";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterable-to-stream/-/iterable-to-stream-1.0.1.tgz";
        sha512 = "O62gD5ADMUGtJoOoM9U6LQ7i4byPXUNoHJ6mqsmkQJcom331ZJGDApWgDESWyBMEHEJRjtHozgIiTzYo9RU4UA==";
      };
    };
    "js-xxhash-1.0.4" = {
      name = "js-xxhash";
      packageName = "js-xxhash";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-xxhash/-/js-xxhash-1.0.4.tgz";
        sha512 = "S/6Oo7ruxx5k8m4qlMnbpwQdJjRsvvfcIhIk1dA9c5y5GNhYHKYKu9krEK3QgBax6CxJuf4gRL2opgLkdzWIKg==";
      };
    };
    "json-parser-1.1.5" = {
      name = "json-parser";
      packageName = "json-parser";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parser/-/json-parser-1.1.5.tgz";
        sha1 = "e62ec5261d1a6a5fc20e812a320740c6d9005677";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "make-dir-3.0.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-3.0.0.tgz";
        sha512 = "grNJDhb8b1Jm1qeqW5R/O63wUo4UXo2v2HMic6YT9i/HBlF93S8jkMgH7yugvY9ABDShH4VZMn8I+U8+fCNegw==";
      };
    };
    "micromatch-4.0.2" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.2.tgz";
        sha512 = "y7FpHSbMUMoyPbYUSzO6PaZ6FyRnQOpHuKwbo1G+Knck95XVU4QAiKdGEnj5wwoS7PlOgthX/09u5iFJ+aYf5Q==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "picomatch-2.0.7" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.0.7.tgz";
        sha512 = "oLHIdio3tZ0qH76NybpeneBhYVj0QFTfXEFTc/B3zKQspYfYYkWYgFsmzo+4kvId/bQRcNkVeguI3y+CD22BtA==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "unique-string-2.0.0" = {
      name = "unique-string";
      packageName = "unique-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-string/-/unique-string-2.0.0.tgz";
        sha512 = "uNaeirEPvpZWSgzwsPGtU2zVSTrn/8L5q/IexZmH0eH6SA73CmAA5U4GwORTxQAZs95TAXLNqeLoPPNO5gZfWg==";
      };
    };
    "universalify-0.1.2" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
        sha512 = "rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
      };
    };
    "vscode-uri-2.0.3" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.0.3.tgz";
        sha512 = "4D3DI3F4uRy09WNtDGD93H9q034OHImxiIcSq664Hq1Y1AScehlP3qqZyTkX/RWxeu0MRMHGkrxYqm2qlDF/aw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "write-file-atomic-3.0.0" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-3.0.0.tgz";
        sha512 = "EIgkf60l2oWsffja2Sf2AL384dx328c0B+cIYPTQq5q2rOYuDV00/iPFBOUiDKKwKMOhkymH8AidPaRvzfxY+Q==";
      };
    };
    "xdg-basedir-4.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-4.0.0.tgz";
        sha512 = "PSNhEJDejZYV7h50BohL09Er9VaIefr2LMAf3OEmpCkjOi34eYyQYAXUTjEQtZJTKcF0E2UKTh+osDLsgNim9Q==";
      };
    };
  };
in
{
  "cspell-4.0.28" = nodeEnv.buildNodePackage {
    name = "cspell";
    packageName = "cspell";
    version = "4.0.28";
    src = fetchurl {
      url = "https://registry.npmjs.org/cspell/-/cspell-4.0.28.tgz";
      sha512 = "2YH8pOUnaGCjHHKKUC2K247nAKx2/ah/JsyMYgSe0U3R1Lokl6+HwTsU2+I01o8u5GbM5sLjxsQRPzceYQkzLg==";
    };
    dependencies = [
      sources."ansi-styles-3.2.1"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commander-2.20.0"
      sources."comment-json-1.1.3"
      sources."concat-map-0.0.1"
      sources."configstore-5.0.0"
      sources."crypto-random-string-2.0.0"
      sources."cspell-dict-companies-1.0.14"
      sources."cspell-dict-cpp-1.1.23"
      sources."cspell-dict-django-1.0.12"
      sources."cspell-dict-elixir-1.0.10"
      sources."cspell-dict-en-gb-1.1.11"
      sources."cspell-dict-en_us-1.2.18"
      sources."cspell-dict-fullstack-1.0.17"
      sources."cspell-dict-golang-1.1.12"
      sources."cspell-dict-haskell-1.0.2"
      sources."cspell-dict-html-symbol-entities-1.0.11"
      sources."cspell-dict-java-1.0.10"
      sources."cspell-dict-latex-1.0.11"
      sources."cspell-dict-lorem-ipsum-1.0.10"
      sources."cspell-dict-php-1.0.11"
      sources."cspell-dict-powershell-1.0.2"
      sources."cspell-dict-python-1.0.14"
      sources."cspell-dict-rust-1.0.10"
      sources."cspell-dict-scala-1.0.9"
      sources."cspell-glob-0.1.11"
      sources."cspell-io-4.0.17"
      sources."cspell-lib-4.0.25"
      sources."cspell-trie-lib-4.0.15"
      sources."cspell-util-bundle-4.0.5"
      sources."dot-prop-5.1.0"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-2.7.3"
      sources."fill-range-7.0.1"
      sources."fs-extra-8.1.0"
      sources."fs.realpath-1.0.0"
      sources."gensequence-2.1.3"
      sources."get-stdin-7.0.0"
      sources."glob-7.1.4"
      sources."graceful-fs-4.2.2"
      sources."has-flag-3.0.0"
      sources."iconv-lite-0.4.24"
      sources."imurmurhash-0.1.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-number-7.0.0"
      sources."is-obj-2.0.0"
      sources."is-typedarray-1.0.0"
      sources."iterable-to-stream-1.0.1"
      sources."js-xxhash-1.0.4"
      sources."json-parser-1.1.5"
      sources."jsonfile-4.0.0"
      sources."make-dir-3.0.0"
      sources."micromatch-4.0.2"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."picomatch-2.0.7"
      sources."safer-buffer-2.1.2"
      sources."semver-6.3.0"
      sources."signal-exit-3.0.2"
      sources."supports-color-5.5.0"
      sources."to-regex-range-5.0.1"
      sources."typedarray-to-buffer-3.1.5"
      sources."unique-string-2.0.0"
      sources."universalify-0.1.2"
      sources."vscode-uri-2.0.3"
      sources."wrappy-1.0.2"
      sources."write-file-atomic-3.0.0"
      sources."xdg-basedir-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Spelling Checker for Code!";
      homepage = "https://github.com/streetsidesoftware/cspell#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}