# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, lib, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ata_piix"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
    ];
  };

  fileSystems."/nix/store" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = [
      "subvol=@nix@store"
      "compress=zstd"
      "ro"
    ];
  };

  zramSwap = {
    enable = true;
    memoryPercent = 99;
    numDevices = 1;
  };

  nix = {
    maxJobs = 1;
    buildCores = 1;
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
